### PR TITLE
Added README.

### PR DESCRIPTION
**Pull request by patriksvensson**

### CODE REVIEW

**Comment by patriksvensson** [comment]
@agc93 Would you mind taking a look at this?

**Comment by agc93** [comment]
Looks good enough to start with to me. Maybe worth calling out that the same process to create ping/pong can be used to create any command? Just makes it clearer.

We'll want to pull together some proper docs including hosting and extensibility which I'll try and get a start on over the next few days..

**Comment by patriksvensson** [comment]
@agc93 Don't you think that's implied? 

Sounds awesome with the docs. What do you want to use? Wyam or DocFX?

**Comment by patriksvensson** [comment]
@agc93 I went ahead and merged this since I'm having a bit of writers block 😄

**Comment by agc93** [comment]
Personally, I'm a DocFX fan but I'm happy to try out Wyam. I'll just do up some Markdown and it can work with either

**Pull request merged**
